<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Thesis.OpenXml\Thesis.OpenXml.csproj" />
    <ProjectReference Include="..\Thesis.Profile\Thesis.Profile.csproj" />
    <ProjectReference Include="..\Thesis.Session\Thesis.Session.csproj" />
    <ProjectReference Include="..\Thesis.Schema\Thesis.Schema.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
