internal static partial class Program
{
    private static readonly (string Name, Action Test)[] Tests =
    [
        ("JSON roundtrip uses camelCase and enum strings", JsonRoundtripUsesCamelCaseAndEnumStrings),
        ("Template profile rules serialize as camelCase JSON", TemplateProfileRulesSerializeAsCamelCaseJson),
        ("SessionPaths resolves expected filenames", SessionPathsResolvesExpectedFilenames),
        ("SessionInitializer creates workspace files and refuses existing workspace", SessionInitializerCreatesFilesAndRefusesExistingWorkspace),
        ("SessionInitializer refuses non-empty stale workspace", SessionInitializerRefusesNonEmptyStaleWorkspace),
        ("SessionInitializer refuses locked workspace", SessionInitializerRefusesLockedWorkspace),
        ("SessionInitializer releases lock after validation errors", SessionInitializerReleasesLockAfterValidationErrors),
        ("CLI run reads request JSON and returns success JSON", CliRunReadsRequestJsonAndReturnsSuccessJson),
        ("CLI run dry-run previews micro edits without changing DOCX", CliRunDryRunPreviewsMicroEditsWithoutChangingDocx),
        ("CLI run execute can replace multiple paragraph text matches", CliRunExecuteCanReplaceMultipleParagraphTextMatches),
        ("CLI run execute applies micro edits and creates snapshot", CliRunExecuteAppliesMicroEditsAndCreatesSnapshot),
        ("CLI run execute aborts transaction on operation error", CliRunExecuteAbortsTransactionOnOperationError),
        ("CLI run wrong typed target returns operation diagnostic", CliRunWrongTypedTargetReturnsOperationDiagnostic),
        ("CLI run rejects invalid run font size", CliRunRejectsInvalidRunFontSize),
        ("CLI validate suggests profile role fixes", CliValidateSuggestsProfileRoleFixes),
        ("CLI run execute inserts deletes and moves paragraphs", CliRunExecuteInsertsDeletesAndMovesParagraphs),
        ("CLI run dry-run previews insert paragraph without changing DOCX", CliRunDryRunPreviewsInsertParagraphWithoutChangingDocx),
        ("CLI run execute applies paragraph format operations", CliRunExecuteAppliesParagraphFormatOperations),
        ("CLI run execute clears direct formatting and sets page break before", CliRunExecuteClearsDirectFormattingAndSetsPageBreakBefore),
        ("CLI run execute inserts and deletes table rows", CliRunExecuteInsertsAndDeletesTableRows),
        ("CLI run execute inserts image paragraph", CliRunExecuteInsertsImageParagraph),
        ("CLI run execute adds page break bookmark and footnote", CliRunExecuteAddsPageBreakBookmarkAndFootnote),
        ("CLI run execute applies thesis document operations", CliRunExecuteAppliesThesisDocumentOperations),
        ("CLI run execute inserts and deletes table columns", CliRunExecuteInsertsAndDeletesTableColumns),
        ("CLI run rejects invalid structure operations", CliRunRejectsInvalidStructureOperations),
        ("CLI run rejects deleting only table row", CliRunRejectsDeletingOnlyTableRow),
        ("CLI run execute applies profile page setup", CliRunExecuteAppliesProfilePageSetup),
        ("CLI run applyProfilePageSetup supports overrides and dry-run", CliRunApplyProfilePageSetupSupportsOverridesAndDryRun),
        ("CLI run applyProfilePageSetup returns format missing", CliRunApplyProfilePageSetupReturnsFormatMissing),
        ("CLI run resolveTarget finds paragraphs by styleId", CliRunResolveTargetFindsParagraphsByStyleId),
        ("CLI run resolveTarget is read-only in execute mode", CliRunResolveTargetIsReadOnlyInExecuteMode),
        ("CLI run execute resolveTarget does not create default snapshot", CliRunExecuteResolveTargetDoesNotCreateDefaultSnapshot),
        ("CLI run paragraph operation rejects table target", CliRunParagraphOperationRejectsTableTarget),
        ("CLI run dry-run previews applyProfileRole without changing DOCX", CliRunDryRunPreviewsApplyProfileRoleWithoutChangingDocx),
        ("CLI run dry-run previews actual applyProfileRole after format", CliRunDryRunPreviewsActualApplyProfileRoleAfterFormat),
        ("CLI run applyProfileRole returns role_not_found", CliRunApplyProfileRoleReturnsRoleNotFound),
        ("CLI run applyProfileRole rejects table target", CliRunApplyProfileRoleRejectsTableTarget),
        ("CLI run applyProfileRole returns format missing", CliRunApplyProfileRoleReturnsFormatMissing),
        ("CLI run execute applies profile role formatting", CliRunExecuteAppliesProfileRoleFormatting),
        ("CLI run applyProfileRole uses role policy format", CliRunApplyProfileRoleUsesRolePolicyFormat),
        ("CLI run applyProfileRole uses format cluster format", CliRunApplyProfileRoleUsesFormatClusterFormat),
        ("CLI run applyProfileRole format overrides profile values", CliRunApplyProfileRoleFormatOverridesProfileValues),
        ("CLI run applyProfileRole uses profile override role aliases", CliRunApplyProfileRoleUsesProfileOverrideRoleAliases),
        ("CLI run applyProfileRole rejects invalid override format", CliRunApplyProfileRoleRejectsInvalidOverrideFormat),
        ("CLI run applyProfileRole rejects invalid override style", CliRunApplyProfileRoleRejectsInvalidOverrideStyle),
        ("CLI run applyProfileRole rejects invalid override font size", CliRunApplyProfileRoleRejectsInvalidOverrideFontSize),
        ("CLI run applyProfileRole rejects invalid override values in dry-run", CliRunApplyProfileRoleRejectsInvalidOverrideValuesInDryRun),
        ("CLI run applyProfileRole accepts extracted lowercase enum values", CliRunApplyProfileRoleAcceptsExtractedLowercaseEnumValues),
        ("CLI run dry-run previews applyProfileTable without changing DOCX", CliRunDryRunPreviewsApplyProfileTableWithoutChangingDocx),
        ("CLI run execute applies profile table formatting", CliRunExecuteAppliesProfileTableFormatting),
        ("CLI run applyProfileTable uses named archetype", CliRunApplyProfileTableUsesNamedArchetype),
        ("CLI run applyProfileTable uses matching archetype when default is missing", CliRunApplyProfileTableUsesMatchingArchetypeWhenDefaultIsMissing),
        ("CLI run applyProfileTable returns format missing", CliRunApplyProfileTableReturnsFormatMissing),
        ("CLI run execute applies table micro operations", CliRunExecuteAppliesTableMicroOperations),
        ("CLI run table border update preserves existing sides", CliRunTableBorderUpdatePreservesExistingSides),
        ("CLI run table border update can set one side on bare table", CliRunTableBorderUpdateCanSetOneSideOnBareTable),
        ("CLI run dry-run previews table cell text without changing DOCX", CliRunDryRunPreviewsTableCellTextWithoutChangingDocx),
        ("CLI run applyThreeLineTable sets academic borders", CliRunApplyThreeLineTableSetsAcademicBorders),
        ("CLI run table cell operation rejects table target", CliRunTableCellOperationRejectsTableTarget),
        ("CLI run returns profile_invalid for malformed workspace profile", CliRunReturnsProfileInvalidForMalformedWorkspaceProfile),
        ("CLI run returns profile_invalid for structurally invalid workspace profile", CliRunReturnsProfileInvalidForStructurallyInvalidWorkspaceProfile),
        ("CLI run returns profile_invalid for null role evidence", CliRunReturnsProfileInvalidForNullRoleEvidence),
        ("CLI run returns profile_invalid for null profile rule containers", CliRunReturnsProfileInvalidForNullProfileRuleContainers),
        ("CLI run returns profile_invalid for malformed role format range", CliRunReturnsProfileInvalidForMalformedRoleFormatRange),
        ("CLI run returns profile_invalid for malformed format clusters", CliRunReturnsProfileInvalidForMalformedFormatClusters),
        ("CLI run resolveTarget finds role evidence from profile", CliRunResolveTargetFindsRoleEvidenceFromProfile),
        ("CLI run role target uses role policies when evidence is missing", CliRunRoleTargetUsesRolePoliciesWhenEvidenceIsMissing),
        ("CLI run role policy target honors afterHeading position", CliRunRolePolicyTargetHonorsAfterHeadingPosition),
        ("CLI run role policy target matches style outline levels", CliRunRolePolicyTargetMatchesStyleOutlineLevels),
        ("CLI run role policy target matches paragraph format", CliRunRolePolicyTargetMatchesParagraphFormat),
        ("CLI run role target uses format clusters when policies are missing", CliRunRoleTargetUsesFormatClustersWhenPoliciesAreMissing),
        ("CLI run role target uses heading format cluster", CliRunRoleTargetUsesHeadingFormatCluster),
        ("CLI run profileOverrides roleAliases resolve profile role", CliRunProfileOverridesRoleAliasesResolveProfileRole),
        ("CLI run role target merges multiple matching profile entries", CliRunRoleTargetMergesMultipleMatchingProfileEntries),
        ("CLI run role afterHeading resolves shifted paragraph", CliRunRoleAfterHeadingResolvesShiftedParagraph),
        ("CLI run sectionRange resolves paragraphs between role anchors", CliRunSectionRangeResolvesParagraphsBetweenRoleAnchors),
        ("CLI run sectionRange rejects ambiguous role anchor", CliRunSectionRangeRejectsAmbiguousRoleAnchor),
        ("CLI run paragraphText regex resolves chapter headings", CliRunParagraphTextRegexResolvesChapterHeadings),
        ("CLI run resolves paragraphId headingPath within and format targets", CliRunResolvesAdvancedTargets),
        ("CLI run resolveTarget finds table cells", CliRunResolveTargetFindsTableCells),
        ("CLI run requireSingleMatch blocks ambiguous style target", CliRunRequireSingleMatchBlocksAmbiguousStyleTarget),
        ("CLI run wrong typed section range anchor returns operation diagnostic", CliRunWrongTypedSectionRangeAnchorReturnsOperationDiagnostic),
        ("CLI run refuses replacing complex paragraph structure", CliRunRefusesReplacingComplexParagraphStructure),
        ("CLI run execute refuses locked workspace", CliRunExecuteRefusesLockedWorkspace),
        ("CLI unknown command returns JSON error", CliUnknownCommandReturnsJsonError),
        ("CLI operations list returns operation metadata", CliOperationsListReturnsOperationMetadata),
        ("CLI operations sample returns executable request JSON", CliOperationsSampleReturnsExecutableRequestJson),
        ("CLI operations sample rejects unknown operation", CliOperationsSampleRejectsUnknownOperation),
        ("Snapshot creates next copy, increments counter, and returns info", SnapshotCreatesNextCopyIncrementsCounterAndReturnsInfo),
        ("Rollback restores working document bytes", RollbackRestoresWorkingDocumentBytes),
        ("Rollback missing snapshot returns JSON error", RollbackMissingSnapshotReturnsJsonError),
        ("Export copies working document and leaves original unchanged", ExportCopiesWorkingDocumentAndLeavesOriginalUnchanged),
        ("Export to original path is refused", ExportToOriginalPathIsRefused),
        ("Export to working path is refused", ExportToWorkingPathIsRefused),
        ("Export inside workspace is refused", ExportInsideWorkspaceIsRefused),
        ("Inspect returns session info and snapshot list", InspectReturnsSessionInfoAndSnapshotList),
        ("Mutating commands refuse existing lock and inspect still works", MutatingCommandsRefuseExistingLockAndInspectStillWorks),
        ("Corrupt session returns JSON error", CorruptSessionReturnsJsonError),
        ("Tampered session paths return JSON error", TamperedSessionPathsReturnJsonError),
        ("Missing workspace files return JSON errors", MissingWorkspaceFilesReturnJsonErrors),
        ("Snapshot and rollback reject traversal identifiers", SnapshotAndRollbackRejectTraversalIdentifiers),
        ("Snapshot refuses to overwrite existing target", SnapshotRefusesToOverwriteExistingTarget),
        ("Snapshot removes orphan when session save fails", SnapshotRemovesOrphanWhenSessionSaveFails),
        ("Rollback ambiguous suffix returns JSON error", RollbackAmbiguousSuffixReturnsJsonError),
        ("Export to missing parent directory returns JSON error", ExportToMissingParentDirectoryReturnsJsonError),
        ("Inspect is read-only when lock exists", InspectIsReadOnlyWhenLockExists),
        ("OpenXml inspector reads paragraphs, styles, numbering, sections, and tables", OpenXmlInspectorReadsDocumentMap),
        ("OpenXml inspector reads paragraph and run format samples", OpenXmlInspectorReadsParagraphAndRunFormatSamples),
        ("OpenXml inspector falls back to complex script font size", OpenXmlInspectorFallsBackToComplexScriptFontSize),
        ("OpenXml inspector reads style usage and outline facts", OpenXmlInspectorReadsStyleUsageAndOutlineFacts),
        ("OpenXml inspector reads outline facts from style definitions", OpenXmlInspectorReadsOutlineFactsFromStyleDefinitions),
        ("OpenXml inspector reads table format samples", OpenXmlInspectorReadsTableFormatSamples),
        ("CLI inspect includes document map for DOCX workspaces", CliInspectIncludesDocumentMapForDocxWorkspaces),
        ("CLI inspect reports JSON warning when document map is unavailable", CliInspectReportsJsonWarningWhenDocumentMapUnavailable),
        ("Template profile builder returns typed profile with semantic roles", TemplateProfileBuilderReturnsTypedProfileWithSemanticRoles),
        ("Template profile builder copies role format samples", TemplateProfileBuilderCopiesRoleFormatSamples),
        ("Template profile builder infers role policies", TemplateProfileBuilderInfersRolePolicies),
        ("Template profile builder infers direct format roles without semantic styles", TemplateProfileBuilderInfersDirectFormatRolesWithoutSemanticStyles),
        ("Template profile builder infers expanded semantic roles", TemplateProfileBuilderInfersExpandedSemanticRoles),
        ("Template profile builder clusters paragraph formats", TemplateProfileBuilderClustersParagraphFormats),
        ("Template profile builder groups multiple table archetypes", TemplateProfileBuilderGroupsMultipleTableArchetypes),
        ("Template profile builder copies table format samples", TemplateProfileBuilderCopiesTableFormatSamples),
        ("Template profile builder infers three-line table archetype", TemplateProfileBuilderInfersThreeLineTableArchetype),
        ("Template profile builder reports weak profile diagnostics", TemplateProfileBuilderReportsWeakProfileDiagnostics),
        ("CLI profile extract writes template profile from DOCX", CliProfileExtractWritesTemplateProfileFromDocx),
        ("CLI profile extract supports workspace working document", CliProfileExtractSupportsWorkspaceWorkingDocument),
        ("CLI profile extract validates source and output options", CliProfileExtractValidatesSourceAndOutputOptions),
        ("CLI profile extract refuses unsafe output paths", CliProfileExtractRefusesUnsafeOutputPaths),
        ("CLI profile extract returns JSON error for non-DOCX input", CliProfileExtractReturnsJsonErrorForNonDocxInput),
        ("CLI profile explain summarizes rules and risks", CliProfileExplainSummarizesRulesAndRisks),
        ("CLI profile explain supports workspace profile", CliProfileExplainSupportsWorkspaceProfile),
        ("CLI profile explain validates options and JSON", CliProfileExplainValidatesOptionsAndJson),
        ("CLI profile diff reports structured changes", CliProfileDiffReportsStructuredChanges),
        ("CLI profile diff returns no changes for equivalent profiles", CliProfileDiffReturnsNoChangesForEquivalentProfiles),
        ("CLI profile diff validates inputs", CliProfileDiffValidatesInputs),
        ("CLI finalize plan reports host application steps for fields", CliFinalizePlanReportsHostApplicationStepsForFields),
        ("CLI finalize plan distinguishes generic fields from TOC", CliFinalizePlanDistinguishesGenericFieldsFromToc),
        ("CLI finalize plan is quiet for clean documents", CliFinalizePlanIsQuietForCleanDocuments),
        ("CLI finalize apply validates source options", CliFinalizeApplyValidatesSourceOptions),
        ("CLI finalize apply reports unavailable COM host", CliFinalizeApplyReportsUnavailableComHost),
        ("CLI finalize apply workspace respects session lock", CliFinalizeApplyWorkspaceRespectsSessionLock),
        ("CLI validate host layout reports unavailable COM host", CliValidateHostLayoutReportsUnavailableComHost)
    ];
}
