internal static partial class Program
{
    private static readonly (string Name, Action Test)[] Tests =
    [
        ("JSON roundtrip uses camelCase and enum strings", JsonRoundtripUsesCamelCaseAndEnumStrings),
        ("Template profile rules serialize as camelCase JSON", TemplateProfileRulesSerializeAsCamelCaseJson),
        ("Final audit models serialize as camelCase JSON", FinalAuditModelsSerializeAsCamelCaseJson),
        ("SessionPaths resolves expected filenames", SessionPathsResolvesExpectedFilenames),
        ("SessionInitializer creates workspace files and refuses existing workspace", SessionInitializerCreatesFilesAndRefusesExistingWorkspace),
        ("SessionInitializer refuses non-empty stale workspace", SessionInitializerRefusesNonEmptyStaleWorkspace),
        ("SessionInitializer refuses locked workspace", SessionInitializerRefusesLockedWorkspace),
        ("SessionInitializer releases lock after validation errors", SessionInitializerReleasesLockAfterValidationErrors),
        ("CLI apply runs request and exports DOCX without manual session", CliApplyRunsRequestAndExportsDocxWithoutManualSession),
        ("CLI apply validates options and does not overwrite source", CliApplyValidatesOptionsAndDoesNotOverwriteSource),
        ("CLI validate supports direct doc and profile", CliValidateSupportsDirectDocAndProfile),
        ("CLI direct commands reject invalid profile shape", CliDirectCommandsRejectInvalidProfileShape),
        ("CLI run reads request JSON and returns success JSON", CliRunReadsRequestJsonAndReturnsSuccessJson),
        ("CLI run dry-run previews micro edits without changing DOCX", CliRunDryRunPreviewsMicroEditsWithoutChangingDocx),
        ("CLI run execute can replace multiple paragraph text matches", CliRunExecuteCanReplaceMultipleParagraphTextMatches),
        ("CLI run execute applies micro edits and creates snapshot", CliRunExecuteAppliesMicroEditsAndCreatesSnapshot),
        ("CLI run execute aborts transaction on operation error", CliRunExecuteAbortsTransactionOnOperationError),
        ("CLI run wrong typed target returns operation diagnostic", CliRunWrongTypedTargetReturnsOperationDiagnostic),
        ("CLI run rejects invalid run font size", CliRunRejectsInvalidRunFontSize),
        ("CLI run supports runText target for setRunFormat", CliRunSupportsRunTextTargetForSetRunFormat),
        ("CLI run executes text-level operations", CliRunExecutesTextLevelOperations),
        ("CLI run text operations refuse paragraphs with fields", CliRunTextOperationsRefuseParagraphsWithFields),
        ("CLI run executes table structure operations", CliRunExecutesTableStructureOperations),
        ("CLI run executes field and cleanup operations", CliRunExecutesFieldAndCleanupOperations),
        ("CLI run cleanup operations are idempotent", CliRunCleanupOperationsAreIdempotent),
        ("CLI run executes reference operations", CliRunExecutesReferenceOperations),
        ("CLI run insert reference item renumbers only reference block", CliRunInsertReferenceItemRenumbersOnlyReferenceBlock),
        ("CLI validate suggests profile role fixes", CliValidateSuggestsProfileRoleFixes),
        ("CLI validate suggests page setup fixes", CliValidateSuggestsPageSetupFixes),
        ("CLI validate warns when finalization is still required", CliValidateWarnsWhenFinalizationIsStillRequired),
        ("CLI validate does not warn after recorded host finalization", CliValidateDoesNotWarnAfterRecordedHostFinalization),
        ("CLI validate warns when recorded host finalization is stale", CliValidateWarnsWhenRecordedHostFinalizationIsStale),
        ("CLI validate resolves profile roles against target document", CliValidateResolvesProfileRolesAgainstTargetDocument),
        ("CLI validate uses semantic fallback for template placeholders", CliValidateUsesSemanticFallbackForTemplatePlaceholders),
        ("CLI validate accepts missing styleId when direct formatting matches", CliValidateAcceptsMissingStyleIdWhenDirectFormattingMatches),
        ("CLI validate rejects missing styleId when direct formatting evidence is weak", CliValidateRejectsMissingStyleIdWhenDirectFormattingEvidenceIsWeak),
        ("CLI validate treats appendix role as optional", CliValidateTreatsAppendixRoleAsOptional),
        ("CLI run execute inserts deletes and moves paragraphs", CliRunExecuteInsertsDeletesAndMovesParagraphs),
        ("CLI run dry-run previews insert paragraph without changing DOCX", CliRunDryRunPreviewsInsertParagraphWithoutChangingDocx),
        ("CLI run execute applies paragraph format operations", CliRunExecuteAppliesParagraphFormatOperations),
        ("CLI run execute clears direct formatting and sets page break before", CliRunExecuteClearsDirectFormattingAndSetsPageBreakBefore),
        ("CLI run execute inserts and deletes table rows", CliRunExecuteInsertsAndDeletesTableRows),
        ("CLI run execute inserts image paragraph", CliRunExecuteInsertsImageParagraph),
        ("CLI run execute adds page break bookmark and footnote", CliRunExecuteAddsPageBreakBookmarkAndFootnote),
        ("CLI run execute applies thesis document operations", CliRunExecuteAppliesThesisDocumentOperations),
        ("CLI run execute inserts and deletes table columns", CliRunExecuteInsertsAndDeletesTableColumns),
        ("CLI run rejects invalid structure operations", CliRunRejectsInvalidStructureOperations),
        ("CLI run rejects deleting only table row", CliRunRejectsDeletingOnlyTableRow),
        ("CLI run execute applies profile page setup", CliRunExecuteAppliesProfilePageSetup),
        ("CLI run applyProfilePageSetup supports overrides and dry-run", CliRunApplyProfilePageSetupSupportsOverridesAndDryRun),
        ("CLI run applyProfilePageSetup returns format missing", CliRunApplyProfilePageSetupReturnsFormatMissing),
        ("CLI run resolveTarget finds paragraphs by styleId", CliRunResolveTargetFindsParagraphsByStyleId),
        ("CLI run resolveTarget is read-only in execute mode", CliRunResolveTargetIsReadOnlyInExecuteMode),
        ("CLI run execute resolveTarget does not create default snapshot", CliRunExecuteResolveTargetDoesNotCreateDefaultSnapshot),
        ("CLI run paragraph operation rejects table target", CliRunParagraphOperationRejectsTableTarget),
        ("CLI run dry-run previews applyProfileRole without changing DOCX", CliRunDryRunPreviewsApplyProfileRoleWithoutChangingDocx),
        ("CLI run dry-run previews actual applyProfileRole after format", CliRunDryRunPreviewsActualApplyProfileRoleAfterFormat),
        ("CLI run writeBlock inserts role formatted paragraph", CliRunWriteBlockInsertsRoleFormattedParagraph),
        ("CLI run writeBlock format overrides profile values", CliRunWriteBlockFormatOverridesProfileValues),
        ("CLI run writeBlock can replace template placeholder", CliRunWriteBlockCanReplaceTemplatePlaceholder),
        ("CLI run writeBlock requires role format", CliRunWriteBlockRequiresRoleFormat),
        ("CLI run applyProfileRole returns role_not_found", CliRunApplyProfileRoleReturnsRoleNotFound),
        ("CLI run applyProfileRole rejects table target", CliRunApplyProfileRoleRejectsTableTarget),
        ("CLI run applyProfileRole returns format missing", CliRunApplyProfileRoleReturnsFormatMissing),
        ("CLI run execute applies profile role formatting", CliRunExecuteAppliesProfileRoleFormatting),
        ("CLI run applyProfileRole uses role policy format", CliRunApplyProfileRoleUsesRolePolicyFormat),
        ("CLI run applyProfileRole uses format cluster format", CliRunApplyProfileRoleUsesFormatClusterFormat),
        ("CLI run applyProfileRole format overrides profile values", CliRunApplyProfileRoleFormatOverridesProfileValues),
        ("CLI run applyProfileRole uses profile override role aliases", CliRunApplyProfileRoleUsesProfileOverrideRoleAliases),
        ("CLI run applyProfileRole rejects invalid override format", CliRunApplyProfileRoleRejectsInvalidOverrideFormat),
        ("CLI run applyProfileRole rejects invalid override style", CliRunApplyProfileRoleRejectsInvalidOverrideStyle),
        ("CLI run applyProfileRole rejects invalid override font size", CliRunApplyProfileRoleRejectsInvalidOverrideFontSize),
        ("CLI run applyProfileRole rejects invalid override values in dry-run", CliRunApplyProfileRoleRejectsInvalidOverrideValuesInDryRun),
        ("CLI run applyProfileRole accepts extracted lowercase enum values", CliRunApplyProfileRoleAcceptsExtractedLowercaseEnumValues),
        ("CLI run dry-run previews applyProfileTable without changing DOCX", CliRunDryRunPreviewsApplyProfileTableWithoutChangingDocx),
        ("CLI run execute applies profile table formatting", CliRunExecuteAppliesProfileTableFormatting),
        ("CLI run applyProfileTable uses named archetype", CliRunApplyProfileTableUsesNamedArchetype),
        ("CLI run applyProfileTable uses matching archetype when default is missing", CliRunApplyProfileTableUsesMatchingArchetypeWhenDefaultIsMissing),
        ("CLI run applyProfileTable returns format missing", CliRunApplyProfileTableReturnsFormatMissing),
        ("CLI run execute applies table micro operations", CliRunExecuteAppliesTableMicroOperations),
        ("CLI run table border update preserves existing sides", CliRunTableBorderUpdatePreservesExistingSides),
        ("CLI run table border update can set one side on bare table", CliRunTableBorderUpdateCanSetOneSideOnBareTable),
        ("CLI run dry-run previews table cell text without changing DOCX", CliRunDryRunPreviewsTableCellTextWithoutChangingDocx),
        ("CLI run applyThreeLineTable sets academic borders", CliRunApplyThreeLineTableSetsAcademicBorders),
        ("CLI run table cell operation rejects table target", CliRunTableCellOperationRejectsTableTarget),
        ("CLI run returns profile_invalid for malformed workspace profile", CliRunReturnsProfileInvalidForMalformedWorkspaceProfile),
        ("CLI run returns profile_invalid for structurally invalid workspace profile", CliRunReturnsProfileInvalidForStructurallyInvalidWorkspaceProfile),
        ("CLI run returns profile_invalid for null role evidence", CliRunReturnsProfileInvalidForNullRoleEvidence),
        ("CLI run returns profile_invalid for null profile rule containers", CliRunReturnsProfileInvalidForNullProfileRuleContainers),
        ("CLI run returns profile_invalid for malformed role format range", CliRunReturnsProfileInvalidForMalformedRoleFormatRange),
        ("CLI run returns profile_invalid for malformed format clusters", CliRunReturnsProfileInvalidForMalformedFormatClusters),
        ("CLI run resolveTarget finds role evidence from profile", CliRunResolveTargetFindsRoleEvidenceFromProfile),
        ("CLI run role target uses role policies when evidence is missing", CliRunRoleTargetUsesRolePoliciesWhenEvidenceIsMissing),
        ("CLI run role target ignores cross-document evidence when policy matches", CliRunRoleTargetIgnoresCrossDocumentEvidenceWhenPolicyMatches),
        ("CLI run role target uses semantic fallback for template placeholders", CliRunRoleTargetUsesSemanticFallbackForTemplatePlaceholders),
        ("CLI run role policy target honors afterHeading position", CliRunRolePolicyTargetHonorsAfterHeadingPosition),
        ("CLI run role policy target matches style outline levels", CliRunRolePolicyTargetMatchesStyleOutlineLevels),
        ("CLI run role policy target matches paragraph format", CliRunRolePolicyTargetMatchesParagraphFormat),
        ("CLI run role target uses format clusters when policies are missing", CliRunRoleTargetUsesFormatClustersWhenPoliciesAreMissing),
        ("CLI run role target uses heading format cluster", CliRunRoleTargetUsesHeadingFormatCluster),
        ("CLI run profileOverrides roleAliases resolve profile role", CliRunProfileOverridesRoleAliasesResolveProfileRole),
        ("CLI run role target merges multiple matching profile entries", CliRunRoleTargetMergesMultipleMatchingProfileEntries),
        ("CLI run role afterHeading resolves shifted paragraph", CliRunRoleAfterHeadingResolvesShiftedParagraph),
        ("CLI run sectionRange resolves paragraphs between role anchors", CliRunSectionRangeResolvesParagraphsBetweenRoleAnchors),
        ("CLI run sectionRange rejects ambiguous role anchor", CliRunSectionRangeRejectsAmbiguousRoleAnchor),
        ("CLI run paragraphText regex resolves chapter headings", CliRunParagraphTextRegexResolvesChapterHeadings),
        ("CLI run resolves paragraphId headingPath within and format targets", CliRunResolvesAdvancedTargets),
        ("CLI run resolveTarget finds table cells", CliRunResolveTargetFindsTableCells),
        ("CLI run requireSingleMatch blocks ambiguous style target", CliRunRequireSingleMatchBlocksAmbiguousStyleTarget),
        ("CLI run wrong typed section range anchor returns operation diagnostic", CliRunWrongTypedSectionRangeAnchorReturnsOperationDiagnostic),
        ("CLI run refuses replacing complex paragraph structure", CliRunRefusesReplacingComplexParagraphStructure),
        ("CLI run execute refuses locked workspace", CliRunExecuteRefusesLockedWorkspace),
        ("CLI unknown command returns JSON error", CliUnknownCommandReturnsJsonError),
        ("CLI help commands return usage JSON", CliHelpCommandsReturnUsageJson),
        ("CLI run reports invalid request JSON", CliRunReportsInvalidRequestJson),
        ("CLI operations list returns operation metadata", CliOperationsListReturnsOperationMetadata),
        ("CLI operations sample returns executable request JSON", CliOperationsSampleReturnsExecutableRequestJson),
        ("CLI operations samples match catalog shapes", CliOperationsSamplesMatchCatalogShapes),
        ("CLI operations sample rejects unknown operation", CliOperationsSampleRejectsUnknownOperation),
        ("Snapshot creates next copy, increments counter, and returns info", SnapshotCreatesNextCopyIncrementsCounterAndReturnsInfo),
        ("Rollback restores working document bytes", RollbackRestoresWorkingDocumentBytes),
        ("Rollback missing snapshot returns JSON error", RollbackMissingSnapshotReturnsJsonError),
        ("Export copies working document and leaves original unchanged", ExportCopiesWorkingDocumentAndLeavesOriginalUnchanged),
        ("Export to original path is refused", ExportToOriginalPathIsRefused),
        ("Export to working path is refused", ExportToWorkingPathIsRefused),
        ("Export inside workspace is refused", ExportInsideWorkspaceIsRefused),
        ("Inspect returns session info and snapshot list", InspectReturnsSessionInfoAndSnapshotList),
        ("Mutating commands refuse existing lock and inspect still works", MutatingCommandsRefuseExistingLockAndInspectStillWorks),
        ("Corrupt session returns JSON error", CorruptSessionReturnsJsonError),
        ("Tampered session paths return JSON error", TamperedSessionPathsReturnJsonError),
        ("Missing workspace files return JSON errors", MissingWorkspaceFilesReturnJsonErrors),
        ("Snapshot and rollback reject traversal identifiers", SnapshotAndRollbackRejectTraversalIdentifiers),
        ("Snapshot refuses to overwrite existing target", SnapshotRefusesToOverwriteExistingTarget),
        ("Snapshot removes orphan when session save fails", SnapshotRemovesOrphanWhenSessionSaveFails),
        ("Rollback ambiguous suffix returns JSON error", RollbackAmbiguousSuffixReturnsJsonError),
        ("Export to missing parent directory returns JSON error", ExportToMissingParentDirectoryReturnsJsonError),
        ("Inspect is read-only when lock exists", InspectIsReadOnlyWhenLockExists),
        ("OpenXml inspector reads paragraphs, styles, numbering, sections, and tables", OpenXmlInspectorReadsDocumentMap),
        ("OpenXml inspector reads paragraph and run format samples", OpenXmlInspectorReadsParagraphAndRunFormatSamples),
        ("OpenXml inspector falls back to complex script font size", OpenXmlInspectorFallsBackToComplexScriptFontSize),
        ("OpenXml inspector reads style usage and outline facts", OpenXmlInspectorReadsStyleUsageAndOutlineFacts),
        ("OpenXml inspector reads outline facts from style definitions", OpenXmlInspectorReadsOutlineFactsFromStyleDefinitions),
        ("OpenXml inspector reads table format samples", OpenXmlInspectorReadsTableFormatSamples),
        ("CLI inspect includes document map for DOCX workspaces", CliInspectIncludesDocumentMapForDocxWorkspaces),
        ("CLI inspect reports JSON warning when document map is unavailable", CliInspectReportsJsonWarningWhenDocumentMapUnavailable),
        ("CLI inspect supports direct DOCX documents", CliInspectSupportsDirectDocxDocuments),
        ("CLI inspect extracts comments and requirement hints", CliInspectExtractsCommentsAndRequirementHints),
        ("CLI rules merge applies project rules over profile", CliRulesMergeAppliesProjectRulesOverProfile),
        ("CLI rules merge validates project rules and normalizes null containers", CliRulesMergeValidatesProjectRulesAndNormalizesNullContainers),
        ("CLI content extract writes thesis content and report", CliContentExtractWritesThesisContentAndReport),
        ("CLI content extract uses cover title before school name", CliContentExtractUsesCoverTitleBeforeSchoolName),
        ("CLI content extract refuses unsafe output paths", CliContentExtractRefusesUnsafeOutputPaths),
        ("CLI rehearsal compare reports candidate gaps", CliRehearsalCompareReportsCandidateGaps),
        ("CLI rehearsal compare writes report JSON", CliRehearsalCompareWritesReportJson),
        ("CLI rehearsal compare refuses overwriting inputs", CliRehearsalCompareRefusesOverwritingInputs),
        ("CLI rehearsal compare normalizes TOC page numbers and repeated heading prefixes", CliRehearsalCompareNormalizesTocPageNumbersAndRepeatedHeadingPrefixes),
        ("CLI rehearsal compare does not treat chapter sentences as headings", CliRehearsalCompareDoesNotTreatChapterSentencesAsHeadings),
        ("CLI rehearsal compare ignores field codes and TOC lines when finding content gaps", CliRehearsalCompareIgnoresFieldCodesAndTocLinesWhenFindingContentGaps),
        ("CLI rehearsal compare scopes content gaps to thesis body", CliRehearsalCompareScopesContentGapsToThesisBody),
        ("CLI rehearsal compare does not block on front matter count gaps", CliRehearsalCompareDoesNotBlockOnFrontMatterCountGaps),
        ("CLI rehearsal compare keeps English body paragraphs ending with digits", CliRehearsalCompareKeepsEnglishBodyParagraphsEndingWithDigits),
        ("Final audit builder blocks on validation diagnostics", FinalAuditBuilderBlocksOnValidationDiagnostics),
        ("Final audit builder blocks on rehearsal content gaps", FinalAuditBuilderBlocksOnRehearsalContentGaps),
        ("Final audit builder blocks on rehearsal diagnostics", FinalAuditBuilderBlocksOnRehearsalDiagnostics),
        ("Final audit builder marks no reference as reduced confidence", FinalAuditBuilderMarksNoReferenceAsReducedConfidence),
        ("Final audit builder blocks when reference provided but rehearsal missing", FinalAuditBuilderBlocksWhenReferenceProvidedButRehearsalMissing),
        ("Final audit builder blocks when rehearsal not ready without diagnostics", FinalAuditBuilderBlocksWhenRehearsalNotReadyWithoutDiagnostics),
        ("Final audit builder ready when all evidence passes", FinalAuditBuilderReadyWhenAllEvidencePasses),
        ("Final audit builder includes pipeline artifacts and summaries", FinalAuditBuilderIncludesPipelineArtifactsAndSummaries),
        ("CLI finalize-all validates required arguments", CliFinalizeAllValidatesRequiredArguments),
        ("CLI finalize-all refuses unsafe output paths", CliFinalizeAllRefusesUnsafeOutputPaths),
        ("CLI finalize-all refuses output artifact collision", CliFinalizeAllRefusesOutputArtifactCollision),
        ("CLI finalize-all refuses workdir artifact input collision", CliFinalizeAllRefusesWorkdirArtifactInputCollision),
        ("CLI finalize-all help lists skip host finalize", CliFinalizeAllHelpListsSkipHostFinalize),
        ("CLI finalize-all writes artifacts without host when skipped", CliFinalizeAllWritesArtifactsWithoutHostWhenSkipped),
        ("CLI finalize-all uses reference for blocking content gaps", CliFinalizeAllUsesReferenceForBlockingContentGaps),
        ("CLI finalize-all preserves existing output when rehearsal blocks", CliFinalizeAllPreservesExistingOutputWhenRehearsalBlocks),
        ("CLI finalize-all rehearsal artifacts point to candidate when audit blocks", CliFinalizeAllRehearsalArtifactsPointToCandidateWhenAuditBlocks),
        ("CLI finalize-all reports unavailable host and keeps audit artifacts", CliFinalizeAllReportsUnavailableHostAndKeepsAuditArtifacts),
        ("CLI finalize-all preserves existing output when host fails", CliFinalizeAllPreservesExistingOutputWhenHostFails),
        ("CLI finalize-all preserves existing output when reference invalid", CliFinalizeAllPreservesExistingOutputWhenReferenceInvalid),
        ("CLI assemble preserves template package and writes content", CliAssemblePreservesTemplatePackageAndWritesContent),
        ("CLI assemble preserves template prefix replaces body and drops template tail", CliAssemblePreservesTemplatePrefixReplacesBodyAndDropsTemplateTail),
        ("CLI assemble uses last body section when template has no tail section", CliAssembleUsesLastBodySectionWhenTemplateHasNoTailSection),
        ("CLI assemble refuses unsafe output paths", CliAssembleRefusesUnsafeOutputPaths),
        ("CLI generate creates thesis DOCX from content and final rules", CliGenerateCreatesThesisDocxFromContentAndFinalRules),
        ("CLI generate refuses unsafe output paths", CliGenerateRefusesUnsafeOutputPaths),
        ("CLI generate does not duplicate existing numbering and creates TOC field", CliGenerateDoesNotDuplicateExistingNumberingAndCreatesTocField),
        ("Template profile builder returns typed profile with semantic roles", TemplateProfileBuilderReturnsTypedProfileWithSemanticRoles),
        ("Template profile builder copies role format samples", TemplateProfileBuilderCopiesRoleFormatSamples),
        ("Template profile builder infers role policies", TemplateProfileBuilderInfersRolePolicies),
        ("Template profile builder infers direct format roles without semantic styles", TemplateProfileBuilderInfersDirectFormatRolesWithoutSemanticStyles),
        ("Template profile builder infers expanded semantic roles", TemplateProfileBuilderInfersExpandedSemanticRoles),
        ("Template profile builder clusters paragraph formats", TemplateProfileBuilderClustersParagraphFormats),
        ("Template profile builder groups multiple table archetypes", TemplateProfileBuilderGroupsMultipleTableArchetypes),
        ("Template profile builder copies table format samples", TemplateProfileBuilderCopiesTableFormatSamples),
        ("Template profile builder infers three-line table archetype", TemplateProfileBuilderInfersThreeLineTableArchetype),
        ("Template profile builder reports weak profile diagnostics", TemplateProfileBuilderReportsWeakProfileDiagnostics),
        ("CLI profile extract writes template profile from DOCX", CliProfileExtractWritesTemplateProfileFromDocx),
        ("CLI profile extract returns explanation summary", CliProfileExtractReturnsExplanationSummary),
        ("CLI profile extract supports workspace working document", CliProfileExtractSupportsWorkspaceWorkingDocument),
        ("CLI profile extract validates source and output options", CliProfileExtractValidatesSourceAndOutputOptions),
        ("CLI profile extract refuses unsafe output paths", CliProfileExtractRefusesUnsafeOutputPaths),
        ("CLI profile extract returns JSON error for non-DOCX input", CliProfileExtractReturnsJsonErrorForNonDocxInput),
        ("CLI profile explain summarizes rules and risks", CliProfileExplainSummarizesRulesAndRisks),
        ("CLI profile explain supports workspace profile", CliProfileExplainSupportsWorkspaceProfile),
        ("CLI profile explain validates options and JSON", CliProfileExplainValidatesOptionsAndJson),
        ("CLI profile diff reports structured changes", CliProfileDiffReportsStructuredChanges),
        ("CLI profile diff returns no changes for equivalent profiles", CliProfileDiffReturnsNoChangesForEquivalentProfiles),
        ("CLI profile diff validates inputs", CliProfileDiffValidatesInputs),
        ("CLI finalize plan reports host application steps for fields", CliFinalizePlanReportsHostApplicationStepsForFields),
        ("CLI finalize plan distinguishes generic fields from TOC", CliFinalizePlanDistinguishesGenericFieldsFromToc),
        ("CLI finalize plan is quiet for clean documents", CliFinalizePlanIsQuietForCleanDocuments),
        ("CLI finalize apply validates source options", CliFinalizeApplyValidatesSourceOptions),
        ("CLI finalize apply reports unavailable COM host", CliFinalizeApplyReportsUnavailableComHost),
        ("CLI finalize apply removes copied output when COM host fails", CliFinalizeApplyRemovesCopiedOutputWhenComHostFails),
        ("CLI finalize apply workspace respects session lock", CliFinalizeApplyWorkspaceRespectsSessionLock),
        ("CLI validate host layout reports unavailable COM host", CliValidateHostLayoutReportsUnavailableComHost)
    ];
}
